services:
  - type: web
    name: youtube-translator
    env: python
    region: oregon
    buildCommand: "pip install -r requirements.txt"
    startCommand: "streamlit run app.py --server.port=$PORT --server.address=0.0.0.0"
    envVars:
      - key: GEMINI_API_KEY
        sync: false